kind: Service
apiVersion: v1
metadata:
  name: app-insights-sidecar-webhook
  namespace: kube-system
spec:
  selector:
    app: app-insights-sidecar-webhook
  ports:
    - port: 443
      targetPort: 8443