apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
  labels:
    app: sampleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
        - name: sampleapp
          image: ghcr.io/implodingduck/app-insights-sidecar-sampleapp:latest
          ports:
            - containerPort: 8080
          command: ["/bin/sh"]
          args: ["-c", "node index.js | tee /var/log/app.log"]
          volumeMounts:
            - name: var-logs
              mountPath: /var/log
      volumes:
      - name: var-logs
        emptyDir: {}